### ISSUE TITLE
booting issue hp 430 g5 bios 1.14

### ISSUE THREAD

**Issue by marcovitalemv** [kreizlie/HP-ProBook-430-G5-Hackintosh#11]
hi kreizle. few days ago I have installed your efi in my probook 430 g5 opencore Mojave project.. all go well until yestersay when I have upgraded my BIOS firmware from original 1.03 to the actual 1,14 from HP official site. After the upgrade boot in Mac os has become impossible....after a very long boot time with the progress bar slowly run nothing else happen.
i cannot understand what has happened.. i have tried to replace your EFI folder in my EFI partition again.. but same problem remain. I attach the boot log from opencore
[opencore-2021-03-04-125716.txt](https://github.com/kreizlie/HP-ProBook-430-G5-Hackintosh/files/6083572/opencore-2021-03-04-125716.txt)

do you look at something that can help me ?
can you send me please a flash file of you BIOS if you have the same version of mine ?

I can add that neither USB Mojave  installer can be anymore opened in probbok to make another fresh installing on SSD.....
thanks .. best regards

marco

**Comment by kreizlie** [comment]
Hi friend, you can download previous version on HP website, just look at a link on the lower part of the download section, select the latest 2019 BIOS. Any of 2020 BIOS did not work for me. If anybody managed to use 2020 BIOS, if possible, can share the knowledge here.

**Comment by marcovitalemv** [comment]
Ok thanks.. i ll try this way

**Comment by kreizlie** [comment]
Hi friend, I have made updates to this hackintosh using opencore 0.6.7, I provide a EFI release that you can download.

**Comment by marcovitalemv** [comment]
HI,thanks but I cannot see a whole EFI OpenCOre folder... there is a CLOVER one...

**Comment by kreizlie** [comment]
I put EFI zip file in release, not CLOVER it is used for dumping original ACPI

**Comment by TzeKitKwok** [comment]
> hi kreizle. few days ago I have installed your efi in my probook 430 g5 opencore Mojave project.. all go well until yestersay when I have upgraded my BIOS firmware from original 1.03 to the actual 1,14 from HP official site. After the upgrade boot in Mac os has become impossible....after a very long boot time with the progress bar slowly run nothing else happen.
> i cannot understand what has happened.. i have tried to replace your EFI folder in my EFI partition again.. but same problem remain. I attach the boot log from opencore
> [opencore-2021-03-04-125716.txt](https://github.com/kreizlie/HP-ProBook-430-G5-Hackintosh/files/6083572/opencore-2021-03-04-125716.txt)
> 
> do you look at something that can help me ?
> can you send me please a flash file of you BIOS if you have the same version of mine ?
> 
> I can add that neither USB Mojave installer can be anymore opened in probbok to make another fresh installing on SSD.....
> thanks .. best regards
> 
> marco

Try adding this to ACPI       OC/ACPI
[SSDT-RTC0.aml.zip](https://github.com/kreizlie/HP-ProBook-430-G5-Hackintosh/files/6129764/SSDT-RTC0.aml.zip)

**Comment by TzeKitKwok** [comment]
> Hi friend, you can download previous version on HP website, just look at a link on the lower part of the download section, select the latest 2019 BIOS. Any of 2020 BIOS did not work for me. If anybody managed to use 2020 BIOS, if possible, can share the knowledge here.

Try adding this to ACPI       OC/ACPI
[SSDT-RTC0.aml.zip](https://github.com/kreizlie/HP-ProBook-430-G5-Hackintosh/files/6129764/SSDT-RTC0.aml.zip)

**Comment by kreizlie** [comment]
Ok friend, thank you, will try this later.

**Comment by kreizlie** [comment]
I have upgraded to BIOS 1.14, this SSDT-RTC0.aml is mandatory to boot opencore with the new BIOS. @marcovitalemv you can try this, if this okay for you I am going to close this issue.

**Comment by marcovitalemv** [comment]
Hi guy... It seems ok for me now.. good job
Thanks for all this..

**Comment by kreizlie** [comment]
Thanks to @TzeKitKwok, I am going to close this issue
