### ISSUE TITLE
How to Compile

### ISSUE THREAD

**Issue by itsdexter007** [kreizlie/HP-ProBook-430-G5-Hackintosh#14]

**Comment by itsdexter007** [comment]
How to Compile with new bios as latest release doesnt have a efi for OC or zip

**Comment by anshmishra** [comment]
@kreizlie can you help me too? there is no EFI file in the latest release 8 days ago

**Comment by kreizlie** [comment]
Hi friends, @itsdexter007 @anshmishra I have made a release for the latest version. Please check my BIOS settings on README, adjust your config.plist if you use different BIOS settings.

**Comment by anshmishra** [comment]
@kreizlie another small issue, i hope i can use the Dortania OpenCore guide and Big Sur instead of Big Sur beta right?

**Comment by itsdexter007** [comment]
did you use any special kexts or patches for your ssd? or you used the samsung mac os firmware for this drive?

**Comment by kreizlie** [comment]
@anshmishra yes, you can use macOS Big Sur

**Comment by kreizlie** [comment]
@itsdexter007 I use SATA M.2 version SSD, not NVME
