### ISSUE TITLE
FaceTime and iMessage support?

### ISSUE THREAD

**Issue by anshmishra** [kreizlie/HP-ProBook-430-G5-Hackintosh#16]
Finally, I have installed macOS Big Sur on my laptop. After installing AirportItlwm.kext for my WiFi chip and rebooting, I tried to log-in into my Apple ID via iMessage. It logs in, open iMessage and instantly logs out and asks me to login again. And this cycle repeats. Any fix?

edit - I used opencore configurator to generate SMBIOS and serial and MAC address and others, still doesn't work

**Comment by anshmishra** [comment]
@kreizlie forgot to mention this, but I happen to use Intel(R) Dual Band Wireless-AC 8265 chip, built-in my laptop.

**Comment by kreizlie** [comment]
Sorry I don't use intel WiFi, I replaced my WiFi card with broadcom one and have iMessage working properly.

**Comment by anshmishra** [comment]
@kreizlie did you make any changes to your EFI or did it work out of the box?

**Comment by kreizlie** [comment]
It works out of the box, if yours does not work, try to regenerate your SMBIOS.
