### ISSUE TITLE
Red battery indicator in uncertain times

### ISSUE THREAD

**Issue by mehmetyukcell** [kreizlie/HP-ProBook-430-G5-Hackintosh#3]
Hi Dear Kreizlie, My system: Hp probook 450 G6 Core i7 8565u with uhd 620. My problem is red battery indicator in uncertain times. Also, I used clover bootloader. Would you give advice for opencore?

My EFI: https://drive.google.com/file/d/1meWbYtauTOG6bw8aTRaz8UhAk8mezh6G/view?usp=sharing

**Comment by kreizlie** [comment]
I also have red battery indicator issue, I am trying to solve it by doing some experiments related to BTST method. I am doing some tests with my patches right now.

**Comment by kreizlie** [comment]
Hi friend, it looks like that I have resolved the battery red indicator issue. The problem is with BTST method that generate invalid amperage value and cause macos think that the battery is too low and show a warning message.

**Comment by mehmetyukcell** [comment]
> Hi friend, it looks like that I have resolved the battery red indicator issue. The problem is with BTST method that generate invalid amperage value and cause macos think that the battery is too low and show a warning message.

Can I Used Which ssdt?

**Comment by kreizlie** [comment]
SSDT-BATT and update your config.plist because you have to rename SB.BTST method
