### ISSUE TITLE
Hi, i was wondering how you had replaced the standard WiFi card with that BCM94360CS2?

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [kreizlie/HP-ProBook-430-G5-Hackintosh#5]
Hi, i was wondering how you had replaced the standard WiFi card with that BCM94360CS2? Did you install it in the WiFi card slot and is that the Apple BCM94360CS2 Card??

**Comment by AbdullahAhmed-hackintosh** [comment]
Will you reply?!?!?!

**Comment by kreizlie** [comment]
Hi friend, I use a NGFF (M2.2) adapter from this link
[https://www.aliexpress.com/item/4000768105997.html](url)
