### ISSUE TITLE
How to create the bootable USB?

### ISSUE THREAD

**Issue by anshmishra** [kreizlie/HP-ProBook-430-G5-Hackintosh#9]
im sorry, im very new to this. I wanted to know how to create the bootable USB of Big Sur, without using a Mac because I don't have one at my disposal

thanks

**Comment by anshmishra** [comment]
alright, I somehow was dumb enough to post this. Now, I used CMD(from OpenCore repo)to get the base system. 

Then I copied the EFI to my USB stick. But on booting, it takes me to GRUB instead of booting into Mac installer. Also, it’s not showing the Mac install for some reason

**Comment by kreizlie** [comment]
Sorry friend, I never tried that, I did make all of my macOS installers on a mac machine.

**Comment by anshmishra** [comment]
So I’ll have to make the USB using a Mac machine?

**Comment by kreizlie** [comment]
That wiill help you a lot. To start hacking a hackintosh machine is not easy, so it's better for you to use the right tool to reduce error-solving tasks.
